# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "json", "~>1.8.0"
gem "pirate_command", "~>0.0"
gem "shuttlecraft", "~>0.0"

gem "minitest", "~>4.7", :group => [:development, :test]
gem "rdoc", "~>4.0", :group => [:development, :test]
gem "hoe-bundler", "~>1.2.0", :group => [:development, :test]
gem "hoe", "~>3.7", :group => [:development, :test]

## MANUALLY ADDED
gem 'shoes',  github: 'shoes/shoes4', :ref => '7d0a1eefea601917dd01419b14ded2812d0acb9f'

# vim: syntax=ruby
